import React, { useMemo, useState, useEffect, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import {
  Plus,
  Search,
  Calendar,
  Users,
  MapPin,
  Mail,
  Pencil,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";
import TourWizard from "../features/tour-wizard/TourWizard";
import { getHotels } from "../services/hotelService";
import { getTours, createTour as apiCreateTour, deleteTour as apiDeleteTour, updateTripStatus as apiUpdateStatus } from "../services/tourService";
import { getCities } from "../services/cityService";

/* =========================================================
   SMALL REUSABLE COMPONENTS
========================================================= */

function InfoRow({ icon: Icon, text }) {
  return (
    <div className="d-flex align-items-center gap-2 text-slate-600 fs-8">
      <Icon size={14} className="flex-shrink-0" />

      <span className="text-truncate">
        {text || "—"}
      </span>
    </div>
  );
}

/* =========================================================
   STATUS CONFIGURATION
========================================================= */

const getStatusConfig = (status) => {
  const normalized = (status || "").toLowerCase();

  switch (normalized) {
    case "planning":
    case "upcoming":
      return {
        label: "Planning",
        bg: "bg-amber-50",
        text: "text-amber-700",
        dot: "bg-amber-500",
      };

    case "emails_sent":
    case "ongoing":
      return {
        label: "Emails Sent",
        bg: "bg-violet-50",
        text: "text-violet-700",
        dot: "bg-violet-500",
      };

    case "quotation_received":
      return {
        label: "Quotation Received",
        bg: "bg-sky-50",
        text: "text-sky-700",
        dot: "bg-sky-500",
      };

    case "hotel_confirmed":
      return {
        label: "Hotel Confirmed",
        bg: "bg-emerald-50",
        text: "text-emerald-700",
        dot: "bg-emerald-500",
      };

    case "completed":
      return {
        label: "Completed",
        bg: "bg-teal-50",
        text: "text-teal-700",
        dot: "bg-teal-500",
      };

    case "cancelled":
      return {
        label: "Cancelled",
        bg: "bg-rose-50",
        text: "text-rose-700",
        dot: "bg-rose-500",
      };

    default:
      return {
        label: status || "Planning",
        bg: "bg-amber-50",
        text: "text-amber-700",
        dot: "bg-amber-500",
      };
  }
};

/* =========================================================
   TOUR ID HELPERS
   Example:
   RT|MS|01|26-27

   NOTE:
   This is only a frontend/demo fallback.
   Production IDs should be generated by the backend/database
   to guarantee uniqueness.
========================================================= */

const getFinancialYear = (date = new Date()) => {
  const month = date.getMonth();
  const year = date.getFullYear();

  // Indian financial year starts on April 1.
  const startYear = month >= 3 ? year : year - 1;
  const endYear = startYear + 1;

  const start = String(startYear).slice(-2);
  const end = String(endYear).slice(-2);

  return `${start}-${end}`;
};

const generateNextTourId = (tours = []) => {
  const financialYear = getFinancialYear();

  const matchingNumbers = tours
    .map((tour) => String(tour?.id || ""))
    .filter((id) => id.startsWith("RT|MS|"))
    .filter((id) => id.endsWith(`|${financialYear}`))
    .map((id) => {
      const parts = id.split("|");

      if (parts.length !== 4) {
        return 0;
      }

      const number = Number(parts[2]);

      return Number.isFinite(number) ? number : 0;
    });

  const highestNumber =
    matchingNumbers.length > 0
      ? Math.max(...matchingNumbers)
      : 0;

  const nextNumber = String(highestNumber + 1).padStart(2, "0");

  return `RT|MS|${nextNumber}|${financialYear}`;
};

/* =========================================================
   NORMALIZATION HELPERS
========================================================= */

const normalizeDestinations = (destinations) => {
  if (!Array.isArray(destinations)) {
    return [];
  }

  return destinations.filter(Boolean);
};

const getDestinationCityId = (destination) => {
  if (!destination) {
    return null;
  }

  return (
    destination.cityId ??
    destination.city?.id ??
    destination.id ??
    null
  );
};

const findCity = (cities, cityId) => {
  if (!cityId) {
    return null;
  }

  return cities.find((city) => {
    const currentId = String(city.id);
    const targetId = String(cityId);

    return (
      currentId === targetId ||
      `c-${currentId}` === targetId ||
      currentId === targetId.replace(/^c-/, "")
    );
  });
};

const getTourClientName = (tour) => {
  return (
    tour?.clientName ||
    tour?.client?.name ||
    tour?.client?.fullName ||
    tour?.name ||
    "Unnamed Client"
  );
};

const getTourEmail = (tour) => {
  return tour?.email || tour?.client?.email || "";
};

const getTourPhone = (tour) => {
  return tour?.phone || tour?.client?.phone || "";
};

const getTravelerCount = (tour) => {
  return (
    tour?.travelers ??
    tour?.numberOfTravelers ??
    tour?.pax ??
    0
  );
};

/* =========================================================
   MAIN COMPONENT
========================================================= */

function Tours() {
  const navigate = useNavigate();

  // ── Data state ────────────────────────────────────────────────────────
  const [toursList, setToursList] = useState([]);
  const [citiesList, setCitiesList] = useState([]);
  const [hotelsData, setHotelsData] = useState([]);
  const [loading, setLoading] = useState(true);

  // ── UI state ──────────────────────────────────────────────────────────
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [isWizardOpen, setIsWizardOpen] = useState(false);
  const [editingTour, setEditingTour] = useState(null);

  // ── Fetch all data from backend on mount ──────────────────────────────
  const fetchTours = useCallback(async () => {
    try {
      const res = await getTours({ limit: 200 });
      // API returns { data: { tours: [...] } }
      const list = res?.data?.tours ?? res?.tours ?? [];
      setToursList(Array.isArray(list) ? list : []);
    } catch (err) {
      console.error("Failed to load tours:", err);
      toast.error("Could not load tours");
    }
  }, []);

  useEffect(() => {
    const init = async () => {
      setLoading(true);
      try {
        await Promise.all([
          fetchTours(),
          getCities({ limit: 200 }).then((res) => {
            const list = res?.data?.cities ?? res?.cities ?? res?.data ?? [];
            setCitiesList(Array.isArray(list) ? list : []);
          }),
          getHotels({ limit: 200 }).then((res) => {
            const list = res?.hotels ?? res?.data?.hotels ?? [];
            setHotelsData(Array.isArray(list) ? list : []);
          }),
        ]);
      } catch (err) {
        console.error("Init error:", err);
      } finally {
        setLoading(false);
      }
    };
    init();
  }, [fetchTours]);

  /* =========================================================
     SEARCH + FILTER
  ========================================================= */

  const filteredTours = useMemo(() => {
    const query = searchTerm.trim().toLowerCase();

    return toursList.filter((tour) => {
      const clientName = getTourClientName(tour).toLowerCase();
      const tourId = String(tour?.id || "").toLowerCase();
      const phone = String(getTourPhone(tour)).toLowerCase();
      const email = String(getTourEmail(tour)).toLowerCase();

      const matchesSearch =
        !query ||
        clientName.includes(query) ||
        tourId.includes(query) ||
        phone.includes(query) ||
        email.includes(query);

      const currentStatus = String(
        tour?.status || "planning"
      ).toLowerCase();

      const matchesStatus =
        statusFilter === "all" ||
        currentStatus === statusFilter.toLowerCase();

      return matchesSearch && matchesStatus;
    });
  }, [toursList, searchTerm, statusFilter]);

  /* =========================================================
     STATUS UPDATE — calls backend PATCH /api/v1/tours/:id/status
  ========================================================= */

  const handleStatusChange = async (tourId, newStatus) => {
    const previousTours = toursList;
    // Optimistic update
    setToursList((prev) =>
      prev.map((t) => (t.id === tourId ? { ...t, tripStatus: newStatus } : t))
    );
    try {
      await apiUpdateStatus(tourId, newStatus);
      toast.success("Tour status updated");
    } catch (error) {
      console.error("Failed to update tour status:", error);
      setToursList(previousTours);
      toast.error("Unable to update tour status");
    }
  };

  /* =========================================================
     DELETE TOUR
  ========================================================= */

  const handleDelete = async (tour) => {
    const confirmed = window.confirm(
      `Delete tour for "${getTourClientName(tour)}"? This cannot be undone.`
    );
    if (!confirmed) return;

    const previousTours = toursList;
    // Optimistic remove
    setToursList((prev) => prev.filter((t) => t.id !== tour.id));
    try {
      await apiDeleteTour(tour.id);
      toast.success("Tour deleted successfully");
    } catch (error) {
      console.error("Failed to delete tour:", error);
      setToursList(previousTours);
      toast.error(error?.response?.data?.message || "Unable to delete tour");
    }
  };

  /* =========================================================
     CREATE / EDIT TOUR
  ========================================================= */

  const handleCreateTour = async (tourData) => {
    if (!tourData) {
      toast.error("Tour information is missing");
      return;
    }

    // The wizard submits wizard-form fields; map them to the backend schema.
    // Backend createTour requires: clientId, destination, packageName, travelDate
    // The Tours wizard stores clientName (no clientId yet), so we persist what we
    // can and refresh the list from the server afterwards.
    try {
      // Build payload the backend understands.
      // destination = first city name from itinerary, or generic fallback
      const firstCityId = tourData.destinations?.[0]?.cityId;
      const firstCity = citiesList.find((c) => String(c.id) === String(firstCityId));
      const destinationName = firstCity?.name || tourData.tourName || "General Tour";

      const payload = {
        // clientId is required — look it up if possible, otherwise skip backend create
        clientId: tourData.clientId || null,
        destination: destinationName,
        packageName: tourData.tourName || tourData.clientName || "Tour Package",
        travelDate: tourData.startDate || tourData.bookingDate || new Date().toISOString(),
        numberOfTravelers: Number(tourData.pax || tourData.travelers || 1),
        remarks: tourData.specialInstructions || null,
      };

      if (payload.clientId) {
        // Persist to backend
        const res = await apiCreateTour(payload);
        const savedTour = res?.data || null;
        if (savedTour) {
          setToursList((prev) => [savedTour, ...prev]);
          toast.success("Tour saved to database");
        } else {
          await fetchTours();
          toast.success("Tour created successfully");
        }
      } else {
        // No clientId — add locally with a temp ID so it shows in UI
        const tempTour = {
          ...tourData,
          id: tourData.id || tourData.fileNumber || generateNextTourId(toursList),
          status: tourData.status || "planning",
          destinations: normalizeDestinations(tourData.destinations),
          clientName: tourData.clientName,
        };
        setToursList((prev) => [tempTour, ...prev]);
        toast.success("Tour added (link a Client to persist to database)");
      }
    } catch (err) {
      console.error("Failed to create tour:", err);
      toast.error(err?.response?.data?.message || "Failed to create tour");
      return;
    }

    setEditingTour(null);
    setIsWizardOpen(false);
  };

  /* =========================================================
     EDIT
  ========================================================= */

  const handleEditClick = (tour) => {
    setEditingTour(tour);
    setIsWizardOpen(true);
  };

  /* =========================================================
     NEW TOUR
  ========================================================= */

  const handleOpenWizard = () => {
    setEditingTour(null);
    setIsWizardOpen(true);
  };

  /* =========================================================
     EMAIL
  ========================================================= */

  const handleSendEmail = (tour) => {
    // Navigate to email center or open email compose
    navigate(`/email-center`);
  };

  /* =========================================================
     DESTINATION HELPERS
  ========================================================= */

  const getDestinationText = (tour) => {
    const destinations = normalizeDestinations(
      tour?.destinations
    );

    const names = destinations
      .map((destination) => {
        /*
         * Some API responses may already contain city names.
         */
        if (destination?.city?.name) {
          return destination.city.name;
        }

        if (destination?.cityName) {
          return destination.cityName;
        }

        const cityId =
          getDestinationCityId(destination);

        const city = findCity(citiesList, cityId);

        return city?.name || "";
      })
      .filter(Boolean);

    if (names.length === 0) {
      return "Main Destination";
    }

    return names.join(", ");
  };

  const getTourImage = (tour) => {
    const destinations = normalizeDestinations(
      tour?.destinations
    );

    const firstDestination = destinations[0];

    const firstCityId =
      getDestinationCityId(firstDestination);

    if (
      firstCityId &&
      cityImageMap?.[firstCityId]
    ) {
      return cityImageMap[firstCityId];
    }

    /*
     * Try resolving through city information in case the
     * destination ID has a different format.
     */
    const city = findCity(citiesList, firstCityId);

    if (city) {
      if (cityImageMap?.[city.id]) {
        return cityImageMap[city.id];
      }

      if (cityImageMap?.[`c-${city.id}`]) {
        return cityImageMap[`c-${city.id}`];
      }

      if (city.image) {
        return city.image;
      }

      if (city.imageUrl) {
        return city.imageUrl;
      }
    }

    const availableImages = Object.values(
      DEMO_IMAGE_MAP || {}
    );

    return (
      availableImages[0] ||
      DEFAULT_TOUR_IMAGE
    );
  };

  /* =========================================================
     UI
  ========================================================= */

  if (loading) {
    return (
      <div className="d-flex align-items-center justify-content-center min-vh-100">
        <div className="text-center">
          <div className="spinner-border text-primary mb-3" style={{ width: "2.5rem", height: "2.5rem" }} />
          <p className="text-secondary fs-7">Loading tours…</p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 md:p-8 space-y-6 bg-tours-light min-vh-100">

      {/* ================= HEADER ================= */}

      <div className="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">

        <div>
          <h1 className="font-display text-3xl font-bold mb-1 text-dark">
            Tours
          </h1>

          <p className="text-secondary mb-0 fs-7">
            Manage every itinerary from planning to completion.
          </p>
        </div>

        <button
          type="button"
          className="btn btn-primary d-flex align-items-center gap-2 px-4 py-2 rounded-xl shadow-sm border-0 fs-7 fw-semibold"
          onClick={handleOpenWizard}
          data-testid="new-tour-btn"
        >
          <Plus size={16} />

          <span>
            New Tour
          </span>
        </button>
      </div>

      {/* ================= TOOLBAR ================= */}

      <div className="card rounded-xl border-soft p-3 bg-white shadow-sm border-0 mb-4">

        <div className="row g-3 align-items-center">

          {/* SEARCH */}

          <div className="col-12 col-md-8 position-relative">

            <div className="input-group border rounded-lg overflow-hidden bg-light shadow-none">

              <span className="input-group-text bg-transparent border-0 text-muted ps-3 pe-2">
                <Search size={16} />
              </span>

              <input
                type="text"
                className="form-control bg-transparent border-0 py-2 fs-7 shadow-none"
                placeholder="Search by client, ID, phone…"
                value={searchTerm}
                onChange={(event) =>
                  setSearchTerm(event.target.value)
                }
                data-testid="tours-search"
              />

            </div>
          </div>

          {/* STATUS FILTER */}

          <div className="col-12 col-md-4">

            <select
              className="form-select py-2 fs-7 text-dark border shadow-none"
              value={statusFilter}
              onChange={(event) =>
                setStatusFilter(event.target.value)
              }
              data-testid="tours-status-filter"
            >
              <option value="all">
                All statuses
              </option>

              <option value="planning">
                Planning
              </option>

              <option value="emails_sent">
                Emails Sent
              </option>

              <option value="quotation_received">
                Quotation Received
              </option>

              <option value="hotel_confirmed">
                Hotel Confirmed
              </option>

              <option value="completed">
                Completed
              </option>

              <option value="cancelled">
                Cancelled
              </option>
            </select>

          </div>
        </div>
      </div>

      {/* ================= EMPTY STATE ================= */}

      {filteredTours.length === 0 ? (

        <div
          className="text-center py-5 border-2 bg-white rounded-2xl d-flex flex-column align-items-center justify-content-center border-soft"
          style={{
            borderStyle: "dashed",
          }}
        >
          <MapPin
            size={32}
            className="text-secondary opacity-50"
          />

          <p className="text-secondary my-3 font-display fs-6">
            No tours match your filters.
          </p>

          {toursList.length === 0 && (
            <button
              type="button"
              className="btn btn-primary d-flex align-items-center gap-2"
              onClick={handleOpenWizard}
            >
              <Plus size={16} />

              Create First Tour
            </button>
          )}
        </div>

      ) : (

        /* ================= TOUR GRID ================= */

        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">

          {filteredTours.map((tour) => {

            const statusConfig =
              getStatusConfig(tour.status);

            const imageSrc =
              getTourImage(tour);

            const destinationText =
              getDestinationText(tour);

            const clientName =
              getTourClientName(tour);

            const email =
              getTourEmail(tour);

            const travelers =
              getTravelerCount(tour);

            return (

              <div
                className="card border-soft bg-white rounded-2xl overflow-hidden shadow-sm tour-card-hover border-0"
                key={tour.id}
                data-testid={`tour-card-${tour.id}`}
              >

                {/* =============== HERO IMAGE =============== */}

                <div
                  className="position-relative"
                  style={{
                    height: "128px",
                  }}
                >

                  <img
                    src={imageSrc}
                    className="w-100 h-100"
                    alt={destinationText}
                    style={{
                      objectFit: "cover",
                    }}
                    onError={(event) => {
                      event.currentTarget.onerror = null;
                      event.currentTarget.src =
                        DEFAULT_TOUR_IMAGE;
                    }}
                  />

                  <div
                    className="position-absolute top-0 start-0 w-100 h-100"
                    style={{
                      background:
                        "linear-gradient(to top, rgba(0,0,0,0.65) 0%, rgba(0,0,0,0) 80%)",
                    }}
                  />

                  {/* CLIENT + TOUR ID */}

                  <div className="position-absolute bottom-0 start-0 p-3 text-white">

                    <span className="text-uppercase tracking-widest font-monospace fs-8 opacity-75 d-block">
                      {tour.id || "—"}
                    </span>

                    <h5
                      className="font-display font-bold text-lg mb-0 text-truncate text-white"
                      style={{
                        maxWidth: "220px",
                      }}
                    >
                      {clientName}
                    </h5>

                  </div>

                  {/* STATUS BADGE */}

                  <div className="position-absolute top-0 end-0 p-2">

                    <span
                      className={`badge rounded-pill px-2 py-1 fs-8 fw-semibold d-flex align-items-center gap-1 ${statusConfig.bg} ${statusConfig.text}`}
                    >

                      <span
                        className={`d-inline-block rounded-circle ${statusConfig.dot}`}
                        style={{
                          width: "6px",
                          height: "6px",
                        }}
                      />

                      {statusConfig.label}

                    </span>

                  </div>

                </div>

                {/* =============== CARD BODY =============== */}

                <div className="p-4">

                  <div className="row g-3">

                    <div className="col-6">

                      <InfoRow
                        icon={Calendar}
                        text={
                          tour.startDate
                            ? String(tour.startDate).slice(0, 10)
                            : "—"
                        }
                      />

                    </div>

                    <div className="col-6">

                      <InfoRow
                        icon={Users}
                        text={`${travelers} travelers`}
                      />

                    </div>

                    <div className="col-6">

                      <InfoRow
                        icon={MapPin}
                        text={destinationText}
                      />

                    </div>

                    <div className="col-6">

                      <InfoRow
                        icon={Mail}
                        text={email || "No email"}
                      />

                    </div>

                  </div>

                  {/* =============== ACTIONS =============== */}

                  <div className="d-flex flex-wrap align-items-center gap-2 pt-3 mt-3 border-top">

                    {/* MANAGE HOTELS */}

                    <button
                      type="button"
                      className="btn btn-sm btn-primary d-inline-flex align-items-center gap-1 py-1 px-2 fs-8"
                      onClick={() => navigate(`/tours/${tour.id}`)}
                      data-testid={`tour-manage-hotels-btn-${tour.id}`}
                    >
                      <span>🏨 Manage Hotels</span>
                    </button>

                    {/* EMAIL */}

                    <button
                      type="button"
                      className="btn btn-sm btn-white border d-inline-flex align-items-center gap-1 py-1 px-2 fs-8 text-dark"
                      onClick={() =>
                        handleSendEmail(tour)
                      }
                      data-testid={`tour-email-btn-${tour.id}`}
                    >
                      <Mail size={12} />

                      <span>
                        Email
                      </span>
                    </button>

                    {/* EDIT */}

                    <button
                      type="button"
                      className="btn btn-sm btn-white border d-inline-flex align-items-center gap-1 py-1 px-2 fs-8 text-dark"
                      onClick={() =>
                        handleEditClick(tour)
                      }
                      data-testid={`tour-edit-btn-${tour.id}`}
                    >
                      <Pencil size={12} />

                      <span>
                        Edit
                      </span>
                    </button>

                    {/* DELETE */}

                    <button
                      type="button"
                      className="btn btn-sm btn-link border-0 text-danger ms-auto p-1 d-inline-flex justify-content-center align-items-center"
                      onClick={() =>
                        handleDelete(tour)
                      }
                      data-testid={`tour-delete-btn-${tour.id}`}
                      aria-label={`Delete ${tour.id}`}
                    >
                      <Trash2 size={14} />
                    </button>

                  </div>

                </div>

              </div>
            );
          })}

        </div>
      )}

      {/* =================================================
          TOUR WIZARD
      ================================================= */}

      <TourWizard
        open={isWizardOpen}
        onOpenChange={(open) => {
          setIsWizardOpen(open);

          if (!open) {
            setEditingTour(null);
          }
        }}
        initialTour={editingTour}
        onSubmit={handleCreateTour}
        cities={citiesList}
        hotels={hotelsData}
        agents={DEMO_AGENTS}
        tours={toursList}
      />

    </div>
  );
}

/* =========================================================
   DEMO / FALLBACK DATA
========================================================= */

const DEMO_CITIES = [
  {
    id: "c-jaipur",
    name: "Jaipur",
    code: "JAI",
  },
  {
    id: "c-goa",
    name: "Goa",
    code: "GOI",
  },
  {
    id: "c-manali",
    name: "Manali",
    code: "MNL",
  },
  {
    id: "c-udaipur",
    name: "Udaipur",
    code: "UDR",
  },
  {
    id: "c-munnar",
    name: "Munnar",
    code: "COK",
  },
];

/* =========================================================
   CITY IMAGES
========================================================= */

const DEMO_IMAGE_MAP = {
  "c-jaipur":
    "https://images.unsplash.com/photo-1477584305590-38cf57beaa83?q=80&w=800&auto=format&fit=crop",

  "c-goa":
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",

  "c-manali":
    "https://images.unsplash.com/photo-1626783011243-d8312914d53c?q=80&w=800&auto=format&fit=crop",

  "c-udaipur":
    "https://images.unsplash.com/photo-1562141971-f921503c5d6c?q=80&w=800&auto=format&fit=crop",

  "c-munnar":
    "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?q=80&w=800&auto=format&fit=crop",
};

const DEFAULT_TOUR_IMAGE =
  "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=800&auto=format&fit=crop";

/* =========================================================
   DEMO HOTELS
========================================================= */

const DEMO_HOTELS = [
  {
    id: 1,
    name: "Taj Rambagh Palace",
    city: "Jaipur",
    category: "Luxury",
    email: "reservations@tajrambagh.com",
  },
  {
    id: 2,
    name: "ITC Rajputana",
    city: "Jaipur",
    category: "5 Star",
    email: "sales@itcrajputana.com",
  },
  {
    id: 3,
    name: "Taj Lake Palace",
    city: "Udaipur",
    category: "Luxury",
    email: "res.lakepalace@tajhotels.com",
  },
  {
    id: 4,
    name: "Umaid Bhawan Palace",
    city: "Jodhpur",
    category: "Luxury",
    email: "res.umaid@tajhotels.com",
  },
];

/* =========================================================
   DEMO AGENTS
========================================================= */

const DEMO_AGENTS = [
  {
    id: "a-1",
    name: "Thomas Cook London",
    country: "United Kingdom",
    email: "london@thomascook.com",
    phone: "+44 20 7946 0958",
  },
  {
    id: "a-2",
    name: "MakeMyTrip Delhi",
    country: "India",
    email: "delhi@makemytrip.com",
    phone: "+91 11 4056 2200",
  },
  {
    id: "a-3",
    name: "TUI Germany",
    country: "Germany",
    email: "info@tui.de",
    phone: "+49 511 567 0",
  },
];

/* =========================================================
   DEMO TOURS

   IDs now follow:
   RT|MS|01|26-27
========================================================= */

const DEMO_TOURS = [
  {
    id: "RT|MS|01|26-27",

    clientName: "Rahul Sharma",

    phone: "9876543210",

    email: "rahul@gmail.com",

    travelers: 4,

    startDate: "2026-10-12",

    endDate: "2026-10-18",

    type: "Family",

    status: "planning",

    destinations: [
      {
        cityId: "c-jaipur",
        nights: 3,
      },
      {
        cityId: "c-udaipur",
        nights: 3,
      },
    ],

    hotels: [
      "Taj Rambagh Palace",
    ],
  },

  {
    id: "RT|MS|02|26-27",

    clientName: "Priyanka Patel",

    phone: "9123456789",

    email: "priyanka.patel@yahoo.com",

    travelers: 2,

    startDate: "2026-11-05",

    endDate: "2026-11-12",

    type: "Honeymoon",

    status: "emails_sent",

    destinations: [
      {
        cityId: "c-goa",
        nights: 7,
      },
    ],

    hotels: [
      "Taj Goa Resort",
    ],
  },

  {
    id: "RT|MS|03|26-27",

    clientName: "Anil Kumble",

    phone: "9845012345",

    email: "anil.kumble@hotmail.com",

    travelers: 5,

    startDate: "2026-12-20",

    endDate: "2026-12-27",

    type: "Family",

    status: "quotation_received",

    destinations: [
      {
        cityId: "c-manali",
        nights: 4,
      },
      {
        cityId: "c-munnar",
        nights: 3,
      },
    ],

    hotels: [
      "Solang Valley Resort",
    ],
  },

  {
    id: "RT|MS|04|26-27",

    clientName: "Siddharth Anand",

    phone: "9988776655",

    email: "sid.anand@gmail.com",

    travelers: 6,

    startDate: "2026-09-01",

    endDate: "2026-09-05",

    type: "Corporate",

    status: "hotel_confirmed",

    destinations: [
      {
        cityId: "c-udaipur",
        nights: 4,
      },
    ],

    hotels: [
      "Taj Lake Palace",
    ],
  },

  {
    id: "RT|MS|05|26-27",

    clientName: "Vikram Malhotra",

    phone: "9812345670",

    email: "vikram@malhotra.org",

    travelers: 2,

    startDate: "2026-05-10",

    endDate: "2026-05-16",

    type: "Adventure",

    status: "completed",

    destinations: [
      {
        cityId: "c-munnar",
        nights: 6,
      },
    ],

    hotels: [
      "Fragrant Nature Resort",
    ],
  },

  {
    id: "RT|MS|06|26-27",

    clientName: "Karan Johar",

    phone: "9822334455",

    email: "karan@dharmaprod.in",

    travelers: 3,

    startDate: "2026-08-15",

    endDate: "2026-08-20",

    type: "Family",

    status: "cancelled",

    destinations: [
      {
        cityId: "c-jaipur",
        nights: 5,
      },
    ],

    hotels: [
      "ITC Rajputana",
    ],
  },
];

/* =========================================================
   EXPORTS
========================================================= */

export default Tours;

export {
  DEMO_TOURS,
  DEMO_CITIES,
  DEMO_IMAGE_MAP,
};